extractor_name: dhis_punjab_disease_tables
extractor_version: "1.0.0"
kafka:
  topic: chip.health.dhis_punjab_weekly.disease_case_report.v1
  bootstrap_servers: localhost:9094
input_sources:
  - dhis_punjab_weekly
